AuthenticationAndAuthorization/Controllers/ClassroomController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AuthenticationAndAuthorization.Controllers
{
    [Authorize]
    public class ClassroomController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AuthenticationAndAuthorization/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuthenticationAndAuthorization</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuthenticationAndAuthorization.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid text-center">
                <div class="col-md-2">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Navbar</a>
                </div>
                <div class="col-md-8 navbar-collapsee collapse show">
                    <div class="d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Classroom" asp-action="Index">Classroom</a>
                                </li>
                            }
                            @if (User.Identities.First().Claims.Any(p => p.Type == "Role" && (p.Value == "Teacher" || p.Value == "Manager")))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Teacherroom" asp-action="Index">Teacher Room</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                <div class="col-md-2 navbar-collapsee collapse show">
                    <div class="loginPartial">
                        <partial name="_LoginStatusPartial" />
                    </div>
                </div>
                <div class="col-md-1">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapsee" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div> 
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AuthenticationAndAuthorization - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AuthenticationAndAuthorization/Views/Shared/_LoginStatusPartial.cshtml
@if (User.Identity.IsAuthenticated)
{
    <form method="post" class="form-inline" action="/Account/Logout">
        <div class="row">
            <div class="col-md-8 d-flex justify-content-end">
                <p class="m-lg-2">Welcome, @User.Identity.Name!</p>
            </div>
            <div class="col-md-4 d-flex justify-content-start">
                <button type="submit" class="btn btn-link">Logout</button>
            </div>
        </div>
    </form>
}
else
{
    <a class="btn btn-link" href="/Account/Login">Login</a>
}